INFO     api_logger:logger.py:21 HTTP method: GET
INFO     api_logger:logger.py:26 Domain: project-x-829879158579.southamerica-west1.run.app
DEBUG    api_logger:logger.py:30 Request URL: https://project-x-829879158579.southamerica-west1.run.app/api/v1/professionals/letras
DEBUG    api_logger:logger.py:31 Request headers: {'accept': 'application/json', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzYyNDYyMDkwLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImRhdmlkLnJvZHJpZ3VlekBwcm9qZWN0LXguY29tIn0.p9BE5tetcx5Wq-bkho3IfkBTYNv2EbFebdmMeHKXSaA'}
DEBUG    api_logger:logger.py:32 Request payload: None
INFO     api_logger:logger.py:39 Timestamp: 2025-10-30 21:18:09
INFO     api_logger:logger.py:44 Status code: 422
DEBUG    api_logger:logger.py:48 Response headers: {'content-type': 'application/json', 'x-cloud-trace-context': '59927af2d02ad3df73c6d85000803f81', 'date': 'Thu, 30 Oct 2025 21:18:09 GMT', 'server': 'Google Frontend', 'Content-Length': '209', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}
DEBUG    api_logger:logger.py:53 Response payload: {'detail': [{'type': 'int_parsing', 'loc': ['path', 'prof_id'], 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': 'letras', 'url': 'https://errors.pydantic.dev/2.8/v/int_parsing'}]}